# build, test, and ftp deploy a jekyll site
name: ci:deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BASEURL: ''
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{secrets.FTP_HOST}}
          username: ${{secrets.FTP_USER}}
          password: ${{secrets.FTP_PASS}}
